### PR TITLE
feat: astro-font - optimize fonts & prevent CLS

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
https://www.launchfa.st/features/astro-font

### CODE REVIEW

**Comment by applejag** [comment]
How does it optimize the fonts?

Hovering over the "close PR" button as this just makes the code less readable. What's wrong with some simple link tags?

**Comment by rishi-raj-jain** [comment]
Feel free to click instead of just hovering on it :)

**Comment by rishi-raj-jain** [comment]
astro-font generates a fallback font relative to your font so that the CLS is none.

**Comment by applejag** [comment]
Don't get why I need it, so I'm closing.

**Pull request closed without merging**
